"""Generate the two context-budget-matched condition TOMLs (IJCKG WP12 step 2).

The matched ablation caps BM25 and dense at exactly the context the KG-augmented
arm retrieved for each task, so the WP5 comparison stops confounding retrieval
quality with budget. Those budgets are a *measurement*, so they are read from the
published WP5 outcomes rather than typed: `context_tokens_median` for
`kg_augmented`, per task, asserted identical across both legs.

Writes conditions/base/{bm25_matched,text_emb_3_large_matched}.toml.
Run: uv run python scripts/wp12_make_matched_conditions.py
"""

from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTCOMES = ROOT / "docs/phase_2/ijckg-2026/wp5_outcomes.csv"
BASE = ROOT / "conditions/base"
TASKS = ["P1", "P2", "P3", "P4", "P5", "P6"]


def budgets() -> dict[str, int]:
    """Per-task KG context, from wp5_outcomes.csv. Both legs must agree."""
    by_task: dict[str, dict[str, int]] = defaultdict(dict)
    with OUTCOMES.open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["condition"] != "kg_augmented":
                continue
            by_task[row["task"]][row["leg"]] = int(row["context_tokens_median"])

    out: dict[str, int] = {}
    for task in TASKS:
        legs = by_task.get(task)
        if not legs:
            sys.exit(f"{OUTCOMES.name}: no kg_augmented row for {task}")
        values = set(legs.values())
        if len(values) != 1:
            # The budget has to be one number per task or the two legs are not
            # running the same ablation. P2/Qwen has a 1,532 x3 / 1,552 x2 spread
            # within the leg, but the medians agree, so this holds.
            sys.exit(f"{task}: legs disagree on the KG context — {legs}")
        budget = values.pop()
        if budget <= 0:
            sys.exit(f"{task}: kg_augmented context_tokens_median is {budget}")
        out[task] = budget
    return out


HEADER = """\
# {cid} — {parent} capped at the KG's own per-task context (IJCKG revision WP12).
#
# GENERATED by scripts/wp12_make_matched_conditions.py from
# docs/phase_2/ijckg-2026/wp5_outcomes.csv. Do not edit by hand: the budgets are a
# measurement of the published kg_augmented arm, not a setting.
#
# Identical to conditions/base/{parent}.toml in every respect except the budget,
# which is per task instead of the assembler's DEFAULT_TOKEN_BUDGET (7000):
# `token_budget_by_task` below is kg_augmented's `context_tokens_median` for that
# task, identical across both legs. A task missing from the table raises rather
# than falling back to 7000 — see `_matched_token_budget` in
# src/generation/orchestrator.py.
#
# An ABLATION, not a sixth baseline: nobody deploys BM25 at 371 tokens. It isolates
# selection quality from budget, and must always be reported beside the
# 7,000-token table. Plan: docs/phase_2/ijckg-2026/wp12_matched_context_plan.md.
#
# Opt-in: not in the orchestrator's default CONDITIONS; run with
# --conditions {cid}.
condition_id = "{cid}"
retriever = "{parent}"
format_variant = "A"
max_rounds = 1

[retriever_params]
"""


def main() -> None:
    b = budgets()
    table = "{ " + ", ".join(f"{t} = {b[t]}" for t in TASKS) + " }"

    for cid, parent, extra in [
        ("bm25_matched", "bm25", ""),
        (
            "text_emb_3_large_matched",
            "text_emb_3_large",
            'embedding_model = "text-embedding-3-large"\n',
        ),
    ]:
        body = HEADER.format(cid=cid, parent=parent) + extra + f"token_budget_by_task = {table}\n"
        (BASE / f"{cid}.toml").write_text(body, encoding="utf-8")
        print(f"wrote {BASE.relative_to(ROOT) / (cid + '.toml')}")

    print("budgets: " + ", ".join(f"{t}={b[t]}" for t in TASKS))


if __name__ == "__main__":
    main()
