"""WP7: score the WP6 annotations — extraction precision / recall / F1.

Scores every complete annotation file in annotations/wp6/ against the graph of
record, checks Project / Library / DEPENDS_ON against package.json at the pinned
SHA, measures agreement on the second-annotator subset if it is done, and states
coverage. Rules: src/evaluation/scoring.py. Deterministic: a re-run on the same
annotations writes identical files.

Writes docs/phase_2/ijckg-2026/wp7_extraction_accuracy.{md,csv}.
Run: uv run python scripts/wp7_score.py [--annotations annotations/wp6] [--out <stem>]
"""

from __future__ import annotations

import argparse
import csv
import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from src.evaluation.annotation import NODE_ORDER, items_by_evidence_file, parse_annotation_file  # noqa: E402
from src.evaluation.kg_dump import load_dump  # noqa: E402
from src.evaluation.scoring import (  # noqa: E402
    Counts,
    aggregate,
    agreement,
    cause_of,
    causes,
    package_check,
    score_file,
)
from wp6_build_annotation_set import PROJECTS, REPOS_ROOT  # noqa: E402

EXAMPLES_PER_TYPE = 5


def fmt(x: float | None) -> str:
    return "—" if x is None else f"{x:.2f}"


def row(label: str, c: Counts) -> str:
    return (f"| {label} | {c.tp} | {c.fp} | {c.fn} | {c.unsure} | "
            f"{fmt(c.precision)} | {fmt(c.recall)} | {fmt(c.f1)} |")


HEAD = "| {} | TP | FP | FN | unsure | P | R | F1 |\n|---|---|---|---|---|---|---|---|"


def type_order(t: str) -> tuple:
    return (0, NODE_ORDER.index(t)) if t in NODE_ORDER else (1, t)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--annotations", default="annotations/wp6")
    ap.add_argument("--out", default="docs/phase_2/ijckg-2026/wp7_extraction_accuracy")
    args = ap.parse_args()
    ann_dir, out = Path(args.annotations), Path(args.out)

    sample = json.loads((ann_dir / "sample.json").read_text(encoding="utf-8"))
    projects = list(sample["quotas"])
    item_sets = {p: items_by_evidence_file(load_dump(sample["graphs"][p]["dump"])) for p in projects}

    scores = []
    for e in sample["files"]:
        parsed = parse_annotation_file((ann_dir / e["file"]).read_text(encoding="utf-8"))
        if (parsed.project, parsed.path) != (e["project"], e["path"]):
            sys.exit(f"{e['file']}: header says {parsed.project}/{parsed.path}")
        scores.append(score_file(parsed, item_sets[e["project"]].by_file[e["path"]], e["stratum"]))
    scored = [s for s in scores if s.scored]
    agg = aggregate(scores)

    # Package-level check against package.json at the pinned SHA.
    pkg = {}
    for p in projects:
        repo = REPOS_ROOT / PROJECTS[p][0]
        sha = sample["graphs"][p]["repo_commit_sha"]
        text = subprocess.run(["git", "-C", str(repo), "show", f"{sha}:./package.json"],
                              check=True, capture_output=True, text=True).stdout
        pkg[p] = package_check(item_sets[p].package, json.loads(text))

    # Second annotator.
    second_dir = ann_dir / "second_annotator"
    pairs = []
    for e in sample["files"]:
        if not e["second_annotator"]:
            continue
        b_text = (second_dir / e["file"]).read_text(encoding="utf-8")
        b = score_file(parse_annotation_file(b_text), item_sets[e["project"]].by_file[e["path"]], e["stratum"])
        a = next(s for s in scores if (s.project, s.path) == (e["project"], e["path"]))
        pairs.append((e, a, b))

    md = [
        "# WP7 — Extraction accuracy (precision / recall / F1)",
        "",
        "> Generated by `scripts/wp7_score.py` from `annotations/wp6/`. Do not edit by hand.",
        "> Rules: `src/evaluation/scoring.py`; protocol: `annotation_guide.md`.",
        "",
        "## Coverage",
        "",
        f"**{len(scored)} of {len(scores)} sampled files scored.** Only complete files count "
        "(`status: done`, every item decided, no syntax errors, pre-fill matching the KG).",
        "",
        "| Repo | Scored / sampled |",
        "|---|---|",
    ]
    for p in projects:
        n = sum(1 for s in scores if s.project == p)
        k = sum(1 for s in scored if s.project == p)
        md.append(f"| {p} | {k} / {n}{' (complete repo)' if k == n else ''} |")
    unscored = [s for s in scores if not s.scored]
    if unscored:
        md += ["", "Not scored:", ""]
        for s in unscored:
            md.append(f"- `{s.project}` `{s.path}`: " + "; ".join(s.problems))

    def section(scope: str, title: str) -> list[str]:
        types = sorted({t for (sc, gk, g, t) in agg if sc == scope and gk == "all" and t != "*"}, key=type_order)
        lines = ["", f"## {title}", "", HEAD.format("Type")]
        lines += [row(f"`{t}`", agg[(scope, "all", "all", t)]) for t in types]
        lines.append(row("**micro-average**", agg.get((scope, "all", "all", "*"), Counts())))
        return lines

    md += section("llm", "Headline: LLM-extracted types")
    md += ["", "### LLM scope by repo and by stratum", "", HEAD.format("Group")]
    # Every group with a scored file gets a row, even with no LLM items (the
    # no-item stratum): a zero is a measurement, not an absence.
    for gk, attr in (("repo", "project"), ("stratum", "stratum")):
        for g in sorted({getattr(s, attr) for s in scored}):
            md.append(row(f"{gk}: {g}", agg.get(("llm", gk, g, "*"), Counts())))
    md += section("deterministic", "Sanity scope: deterministic types (per file)")
    md += ["", "### Package-level, checked against `package.json` at the pinned SHA", "",
           HEAD.format("Repo · type")]
    for p in projects:
        for t, c in pkg[p].items():
            md.append(row(f"{p} · `{t}`", c))

    cz = causes(scores)
    md += ["", "## Error attribution (`# cause:` notes)", ""]
    if cz:
        md += ["| Error | Type | Cause | Count |", "|---|---|---|---|"]
        for (kind, t, cause), n in sorted(cz.items(), key=lambda kv: (kv[0][0], type_order(kv[0][1]), str(kv[0][2]))):
            md.append(f"| {kind} | `{t}` | {cause or 'not tagged'} | {n} |")
    else:
        md.append("No errors in scored files yet.")

    md += ["", "## Error examples", "", f"Up to {EXAMPLES_PER_TYPE} per type and kind, for qualitative analysis.", ""]
    ex = defaultdict(list)
    for s in scored:
        for i, note in s.fp:
            ex[("FP", i.type)].append((s, i, note))
        for i, note in s.fn:
            ex[("FN", i.type)].append((s, i, note))
    if not ex:
        md.append("None yet.")
    for (kind, t) in sorted(ex, key=lambda k: (k[0], type_order(k[1]))):
        md.append(f"- **{kind} `{t}`**")
        for s, i, note in ex[(kind, t)][:EXAMPLES_PER_TYPE]:
            md.append(f"  - `{s.project}` `{s.path}`: `{i.text(s.path)}`" + (f" — {note}" if note else ""))

    schema_fn = [(s, i, n) for s in scored for i, n in s.fn if cause_of(n) == "schema"]
    md += ["", "## Missed items tagged `cause: schema` (feeds WP4b)", ""]
    md += [f"- `{s.project}` `{s.path}`: `{i.text(s.path)}` — {n}" for s, i, n in schema_fn] or ["None yet."]

    aside = [(s, i, r) for s in scored for i, r in s.set_aside]
    conf = [(s, i, r) for s in scored for i, r in s.conflicts]
    md += ["", "## Set aside and conflicts (not counted)", ""]
    md += [f"- set aside: `{s.path}`: `{i.text(s.path)}` — {r}" for s, i, r in aside]
    md += [f"- conflict: `{s.path}`: `{i.text(s.path)}` — {r}" for s, i, r in conf]
    if not aside and not conf:
        md.append("None.")

    md += ["", "## Inter-annotator agreement", ""]
    done_pairs = [(e, a, b) for e, a, b in pairs if a.scored and b.scored]
    if done_pairs:
        md += ["| File | Items | Agree | Cohen's κ | Missed A / B / both |", "|---|---|---|---|---|"]
        for e, a, b in done_pairs:
            g = agreement(a, b)
            md.append(f"| `{e['project']}` `{e['path']}` | {g.items} | {g.agree} | {fmt(g.kappa)} | "
                      f"{g.missed_a} / {g.missed_b} / {g.missed_both} |")
    else:
        md.append(f"Not measured: {len(pairs)} second-annotator files exist, "
                  f"{sum(b.scored for _, _, b in pairs)} of them complete. With no second annotator, "
                  "the scores are **single-annotator, with no agreement measure**.")

    md += [
        "",
        "## Known biases (state these with the scores)",
        "",
        "- **Pre-filled drafts (corrected-draft protocol) bias recall upward.** A missed item has "
        "to be noticed unprompted, while an extracted one only needs confirming. The blind step 1 "
        "reduces this bias but does not remove it.",
        "- **Single annotator** unless the agreement table above has rows.",
        "- **The sample was steered by the types the extractor found.** A type it missed everywhere "
        "could not steer the sample.",
        "- **The no-item stratum is under-sampled.** It has one file per repo, while such files make "
        "up 105 of 283. Report the strata separately.",
        "- **Grain.** `Prop` and `EventHandler` are the two types that are unstable across "
        "re-extractions (WP0 step 7), so their scores carry run-to-run variance as well as error.",
    ]

    csv_rows = [
        {"scope": sc, "group_kind": gk, "group": g, "type": t, "tp": c.tp, "fp": c.fp, "fn": c.fn,
         "unsure": c.unsure, "precision": fmt(c.precision), "recall": fmt(c.recall), "f1": fmt(c.f1)}
        for (sc, gk, g, t), c in sorted(agg.items())
    ]
    csv_rows += [
        {"scope": "package", "group_kind": "repo", "group": p, "type": t, "tp": c.tp, "fp": c.fp, "fn": c.fn,
         "unsure": 0, "precision": fmt(c.precision), "recall": fmt(c.recall), "f1": fmt(c.f1)}
        for p in projects for t, c in pkg[p].items()
    ]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.with_suffix(".md").write_text("\n".join(md) + "\n", encoding="utf-8")
    with out.with_suffix(".csv").open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["scope", "group_kind", "group", "type", "tp", "fp", "fn",
                                          "unsure", "precision", "recall", "f1"])
        w.writeheader()
        w.writerows(csv_rows)
    print("\n".join(md))
    print(f"\nwrote {out.with_suffix('.md')} and {out.with_suffix('.csv')}")


if __name__ == "__main__":
    main()
