"""Phase 2 (code generation) token and USD cost, from experiment_logs/ (IJCKG WP9).

Headline: the WP5 runs (both models, P1-P6, five conditions), per model x condition
and per task, with the classifier (a KG-only, per-task overhead) shown separately.
Also: every Phase 2 run per day x model x provider, to check against the Anthropic
console and the OpenRouter activity page.

Prices and their provenance: src/evaluation/cost.py.

Writes docs/phase_2/ijckg-2026/wp9_phase2_cost.{md,csv}.
Run: uv run python scripts/wp9_phase2_cost.py
"""

from __future__ import annotations

import csv
import json
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.evaluation.cost import (  # noqa: E402
    MODEL_LABEL,
    PRICES,
    PRICES_FETCHED,
    CostReport,
    Tally,
    UnpricedCall,
    by_generator_model,
    match_task,
)
from src.generation.orchestrator import load_task_spec  # noqa: E402

LOGS = Path("experiment_logs")
OUT = Path("docs/phase_2/ijckg-2026/wp9_phase2_cost")
WP5_RUNS = [
    f"{leg}_{suffix}"
    for leg in ("claude_primary", "qwen_robustness")
    for suffix in ("2026-09-18_wp5_p1p3", "2026-09-19_wp5_p1p3_baselines", "2026-09-19_wp5_p4p6")
]
TASKS = ["P1", "P2", "P3", "P4", "P5", "P6"]
CONDITIONS = ["floor", "whole_file", "kg_augmented", "bm25", "text_emb_3_large"]
GEN_MODELS = ["anthropic/claude-sonnet-4-6", "openrouter/qwen/qwen3-coder"]


def records(run: str):
    for f in sorted((LOGS / run).glob("*.jsonl")):
        for line in f.open(encoding="utf-8"):
            if line.strip():
                yield json.loads(line)


def phase2_runs() -> list[str]:
    # extract_* are Phase 1 extraction logs (costed in WP0/WP1), not code generation.
    return sorted(p.name for p in LOGS.iterdir() if p.is_dir() and not p.name.startswith("extract_"))


def usd(x: float) -> str:
    return f"{x:.4f}" if x < 1 else f"{x:.2f}"


def main() -> None:
    specs = {t: load_task_spec(t) for t in TASKS}

    # ---- WP5 headline: every call priced, every LLM call attributed to a task ----
    wp5 = CostReport()
    for run in WP5_RUNS:
        if not (LOGS / run).is_dir():
            sys.exit(f"missing WP5 run {run}")
        for rec in records(run):
            task = match_task(rec, specs)
            if task is None and rec.get("call_purpose") in ("classifier", "generator"):
                sys.exit(f"{run}: a {rec['call_purpose']} call matches no task statement")
            try:
                wp5.add(run, rec, task)
            except UnpricedCall as exc:
                sys.exit(f"{run}: {exc}")

    agg, cands = by_generator_model(wp5, GEN_MODELS)

    def total(key) -> float:
        return sum(t.usd for t in agg[key].values())

    md = [
        "# WP9 — Phase 2 (code generation) token and USD cost",
        "",
        "> Generated by `scripts/wp9_phase2_cost.py` from `experiment_logs/`. Do not edit by hand.",
        f"> Prices: `src/evaluation/cost.py`. OpenRouter prices were fetched on {PRICES_FETCHED}, not at",
        "> call time, so check them against the OpenRouter activity page before quoting.",
        "",
        "## Prices (USD per 1M tokens)",
        "",
        "| Model | Provider | Input | Output |",
        "|---|---|---|---|",
    ]
    for (model, prov), (pin, pout) in PRICES.items():
        md.append(f"| {MODEL_LABEL.get(model, model)} | {prov or 'direct'} | {pin:.3f} | {pout:.3f} |")

    md += [
        "",
        "## WP5, per model and condition",
        "",
        "Runs: " + ", ".join(f"`{r}`" for r in WP5_RUNS) + ".",
        "",
        "Generator tokens are totals over the cell. The classifier is the KG condition's "
        "per-task overhead, and it runs on the generator model.",
        "",
        "| Model | Condition | Candidates | Generator in / out tokens | Classifier in / out | "
        "Embedding tokens | USD | USD per candidate |",
        "|---|---|---|---|---|---|---|---|",
    ]
    csv_rows = []
    for gm in GEN_MODELS:
        model_total = 0.0
        for cond in CONDITIONS:
            key = (gm, cond, None)
            if key not in agg:
                continue
            g, c = agg[key].get("generator", Tally()), agg[key].get("classifier", Tally())
            emb = sum(t.input_tokens for p, t in agg[key].items() if p.startswith("embedding"))
            n = cands[key]
            tot = total(key)
            model_total += tot
            md.append(
                f"| {MODEL_LABEL[gm]} | {cond} | {n} | {g.input_tokens:,} / {g.output_tokens:,} | "
                f"{(f'{c.input_tokens:,} / {c.output_tokens:,}') if c.calls else '—'} | "
                f"{emb:,} | {usd(tot)} | {tot / n:.4f} |"
            )
        md.append(f"| **{MODEL_LABEL[gm]}** | **total** | | | | | **{usd(model_total)}** | |")

    md += [
        "",
        "## WP5, USD per candidate by task",
        "",
        "Classifier and embedding calls are included in the cell they belong to.",
        "",
        "| Model | Condition | " + " | ".join(TASKS) + " |",
        "|---|---|" + "---|" * len(TASKS),
    ]
    for gm in GEN_MODELS:
        for cond in CONDITIONS:
            cells = []
            for task in TASKS:
                key = (gm, cond, task)
                cells.append(f"{total(key) / cands[key]:.4f}" if cands.get(key) else "—")
            md.append(f"| {MODEL_LABEL[gm]} | {cond} | " + " | ".join(cells) + " |")

    for (run, model, cond, task, purpose), t in sorted(wp5.rows.items(), key=lambda kv: tuple(str(x) for x in kv[0])):
        csv_rows.append({
            "run": run, "model": model, "condition": cond, "task": task or "", "call_purpose": purpose,
            "calls": t.calls, "input_tokens": t.input_tokens, "output_tokens": t.output_tokens,
            "usd": f"{t.usd:.6f}",
        })

    # ---- All Phase 2 runs, per day x model x provider (dashboard cross-check) ----
    allrep = CostReport()
    unpriced: dict[tuple, Tally] = defaultdict(Tally)
    for run in phase2_runs():
        for rec in records(run):
            try:
                allrep.add(run, rec, None)
            except UnpricedCall:
                unpriced[(run, rec.get("model_id"), rec.get("openrouter_provider"))].add(rec, 0.0)

    md += [
        "",
        "## All Phase 2 runs, per day, model and provider",
        "",
        "Every run in `experiment_logs/` except Phase 1 extraction (`extract_*`), which WP0/WP1 "
        "costed. This includes the July pilot legs, dry runs and diagnostics. These rows are what "
        "the Anthropic console (by day) and the OpenRouter activity page (by provider) should show.",
        "",
        "| Day (UTC) | Model | Provider | Calls | Input tokens | Output tokens | USD |",
        "|---|---|---|---|---|---|---|",
    ]
    grand = 0.0
    for (day, model, prov), t in sorted(allrep.by_day.items(), key=lambda kv: tuple(str(x) for x in kv[0])):
        if t.calls == 0:
            continue
        grand += t.usd
        md.append(
            f"| {day} | {MODEL_LABEL.get(model, model)} | {prov or 'direct'} | {t.calls} | "
            f"{t.input_tokens:,} | {t.output_tokens:,} | {usd(t.usd)} |"
        )
    md.append(f"| **all** | | | | | | **{usd(grand)}** |")
    md += [
        "",
        "### Reconciliation with the provider statements",
        "",
        "Checked against the Anthropic usage export and the OpenRouter activity export for **2026-09-18 "
        "and 2026-09-19** (the exports are not committed):",
        "",
        "- **Claude, Phase 2:** the console's 18 Sep 13:00 UTC bucket (169,360 / 32,941) and 19 Sep 15:00 + "
        "16:00 buckets (1,079,990 / 67,821) equal the rows above.",
        "- **Claude, extraction (18 Sep, not in this table; see `wp9_cost.md`):** the 03:00–08:00 buckets equal "
        "the extraction logs hour by hour. The 02:00 bucket holds Todoist (829,594 / 16,327) plus 169,746 / "
        "3,089 tokens ($0.56) from the two WP0 test runs, already recorded in WP1's cost check.",
        "- **Qwen3-Coder:** all 70 (18 Sep) and 120 (19 Sep) generations, and per provider the call count, "
        "prompt and completion tokens, equal the rows above. Alibaba, Google and Novita are billed exactly as "
        "priced here. DeepInfra and Venice applied **automatic prompt-cache discounts**, and billed + "
        "`cost_cache` equals the figure here to the cent. The Qwen total was billed $0.1103 against $0.1206 "
        "here on 18 Sep, and $0.2531 against $0.4075 on 19 Sep.",
        "",
        "So the prices and token counts are exact, and **the Qwen USD here is list price before provider "
        "cache discounts, an upper bound** (billed was 68% of it over the two days). The call logs do not "
        "record cached tokens, so the discount cannot be applied per call. The Claude calls had no caching. "
        "Days **other than 2026-09-18 and 2026-09-19** have not been checked against the statements: "
        "the July pilot before them, and the 2026-09-21 WP12 matched-ablation runs after them "
        "(`*_2026-09-21_wp12_matched`, $1.16 Claude + $0.13 Qwen). Those rows are priced by the same "
        "table as the rest and are included in the grand total above.",
    ]
    if unpriced:
        md += ["", "**Unpriced calls** (no price in the table; not in the totals):", ""]
        for (run, model, prov), t in sorted(unpriced.items(), key=lambda kv: tuple(str(x) for x in kv[0])):
            md.append(f"- `{run}`: {model} via {prov or 'direct'}: {t.calls} calls, "
                      f"{t.input_tokens:,} in / {t.output_tokens:,} out")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.with_suffix(".md").write_text("\n".join(md) + "\n", encoding="utf-8")
    with OUT.with_suffix(".csv").open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(csv_rows[0]))
        w.writeheader()
        w.writerows(csv_rows)
    print("\n".join(md))
    print(f"\nwrote {OUT.with_suffix('.md')} and {OUT.with_suffix('.csv')} ({len(csv_rows)} rows)")


if __name__ == "__main__":
    main()
